"""fix validate cable.isolation_id

Revision ID: c6b3275d6d14
Revises: 0822e815ae8b
Create Date: 2025-12-27 19:51:15.383685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b3275d6d14'
down_revision: Union[str, None] = '0822e815ae8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cable', 'isolation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('fk_isolation'), 'cable', type_='foreignkey')
    op.create_foreign_key('fk_isolation', 'cable', 'isolation', ['isolation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_isolation', 'cable', type_='foreignkey')
    op.create_foreign_key(op.f('fk_isolation'), 'cable', 'isolation', ['isolation_id'], ['id'], ondelete='SET NULL')
    op.alter_column('cable', 'isolation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
