"""add_ondelete_twist

Revision ID: ed82952e966a
Revises: e8621f3de18f
Create Date: 2026-02-05 19:59:05.659182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed82952e966a'
down_revision: Union[str, None] = 'e8621f3de18f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_twisting'), 'isolation', type_='foreignkey')
    op.create_foreign_key('fk_twisting', 'isolation', 'twisting', ['twist_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_twisting', 'isolation', type_='foreignkey')
    op.create_foreign_key(op.f('fk_twisting'), 'isolation', 'twisting', ['twist_id'], ['id'])
    # ### end Alembic commands ###
