"""add_models

Revision ID: 08b3b50609d3
Revises: 
Create Date: 2026-02-23 00:30:01.725913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b3b50609d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumoflex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drennage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.CheckConstraint("name ~ '^\\d+x\\d+\\.?\\d*м$'", name='check_format_drennage_name'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marker',
    sa.Column('text', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('construction',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('isolate_plastic_id', sa.Integer(), nullable=False),
    sa.Column('shell_plastic_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], name='fk_color'),
    sa.ForeignKeyConstraint(['isolate_plastic_id'], ['plastic.id'], name='fk_isolate_plastic'),
    sa.ForeignKeyConstraint(['shell_plastic_id'], ['plastic.id'], name='fk_shell_plastic'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='check_name_consrtruction')
    )
    op.create_table('twisting',
    sa.Column('count_wires', sa.Integer(), nullable=False),
    sa.Column('diametr_wires', sa.Float(), nullable=False),
    sa.Column('metall_id', sa.Integer(), nullable=False),
    sa.Column('resistance', sa.Float(), nullable=False),
    sa.Column('step', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['metall_id'], ['metall.id'], name='fk_metall', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('isolation',
    sa.Column('core', sa.String(length=32), nullable=False),
    sa.Column('twist_id', sa.Integer(), nullable=False),
    sa.Column('outer_diametr', sa.Float(), nullable=False),
    sa.Column('inner_diametr', sa.Float(), nullable=False),
    sa.Column('radial', sa.Float(), sa.Computed('(outer_diametr - inner_diametr) / 2', ), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint("core ~ '^\\d+x\\d+\\.?\\d*(м|ф|н|л|с|нс)$'", name='check_format_core'),
    sa.CheckConstraint('inner_diametr < outer_diametr', name='inner_smaller_outer'),
    sa.CheckConstraint('inner_diametr > 0', name='check_inner_diametr'),
    sa.CheckConstraint('radial > 0', name='check_radial'),
    sa.ForeignKeyConstraint(['twist_id'], ['twisting.id'], name='fk_twisting', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cable',
    sa.Column('article', sa.Integer(), nullable=False),
    sa.Column('outer_diametr', sa.Float(), nullable=False),
    sa.Column('inner_diametr', sa.Float(), nullable=False),
    sa.Column('radial', sa.Float(), nullable=False),
    sa.Column('isolation_id', sa.Integer(), nullable=False),
    sa.Column('construction_id', sa.Integer(), nullable=False),
    sa.Column('drennage_id', sa.Integer(), nullable=False),
    sa.Column('alumoflex_id', sa.Integer(), nullable=False),
    sa.Column('marker_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('inner_diametr < outer_diametr', name='inner_smaller_outer'),
    sa.CheckConstraint('inner_diametr > 0', name='check_inner_diametr'),
    sa.CheckConstraint('outer_diametr > 0', name='check_outer_diametr'),
    sa.CheckConstraint('radial > 0', name='check_radial'),
    sa.ForeignKeyConstraint(['alumoflex_id'], ['alumoflex.id'], name='fk_alumoflex'),
    sa.ForeignKeyConstraint(['construction_id'], ['construction.id'], name='fk_construction', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drennage_id'], ['drennage.id'], name='fk_drennage'),
    sa.ForeignKeyConstraint(['isolation_id'], ['isolation.id'], name='fk_isolation', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marker_id'], ['marker.id'], name='fk_marker'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article'),
    sa.UniqueConstraint('article', 'isolation_id', 'construction_id', name='unique_art_and_isolate'),
    sa.UniqueConstraint('article', name='check_article')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cable')
    op.drop_table('isolation')
    op.drop_table('twisting')
    op.drop_table('construction')
    op.drop_table('plastic')
    op.drop_table('metall')
    op.drop_table('marker')
    op.drop_table('drennage')
    op.drop_table('color')
    op.drop_table('alumoflex')
    # ### end Alembic commands ###
