"""add_dep role

Revision ID: ad822a02e951
Revises: d7037994af60
Create Date: 2026-04-04 01:37:18.746468

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad822a02e951'
down_revision: Union[str, Sequence[str], None] = 'd7037994af60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('CABLE', 'TWIST', name='department').create(op.get_bind())
    op.add_column('user', sa.Column('department', postgresql.ENUM('CABLE', 'TWIST', name='department', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'department')
    sa.Enum('CABLE', 'TWIST', name='department').drop(op.get_bind())
    # ### end Alembic commands ###
