"""add_models

Revision ID: d7037994af60
Revises: 
Create Date: 2026-04-03 13:03:10.610172

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7037994af60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumoflex',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drennage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.CheckConstraint("name ~ '^\\d+x\\d+\\.?\\d*м$'", name='check_format_drennage_name'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marker',
    sa.Column('text', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metall',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('second_name', sa.String(), nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'USER', name='userrole', create_type=False), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('construction',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('isolate_plastic_id', sa.Integer(), nullable=False),
    sa.Column('shell_plastic_id', sa.Integer(), nullable=False),
    sa.Column('radial_isolate', sa.Float(), nullable=False),
    sa.Column('radial_shell', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], name='fk_color'),
    sa.ForeignKeyConstraint(['isolate_plastic_id'], ['plastic.id'], name='fk_isolate_plastic'),
    sa.ForeignKeyConstraint(['shell_plastic_id'], ['plastic.id'], name='fk_shell_plastic'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='check_name_consrtruction')
    )
    op.create_table('twisting',
    sa.Column('count_wires', sa.Integer(), nullable=False),
    sa.Column('diametr_wires', sa.Float(), nullable=False),
    sa.Column('diametr_twist', sa.Float(), sa.Computed('CEIL((diametr_wires * sqrt(count_wires)) * 100) / 100', ), nullable=False),
    sa.Column('metall_id', sa.Integer(), nullable=False),
    sa.Column('resistance', sa.Float(), nullable=False),
    sa.Column('step', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['metall_id'], ['metall.id'], name='fk_metall', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cable',
    sa.Column('title', sa.String(), server_default='untitled', nullable=False),
    sa.Column('article', sa.BigInteger(), nullable=False),
    sa.Column('outer_diametr', sa.Float(), nullable=True),
    sa.Column('inner_diametr', sa.Float(), nullable=True),
    sa.Column('twist_id', sa.Integer(), nullable=False),
    sa.Column('construction_id', sa.Integer(), nullable=False),
    sa.Column('drennage_id', sa.Integer(), nullable=False),
    sa.Column('alumoflex_id', sa.Integer(), nullable=False),
    sa.Column('marker_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('article BETWEEN 100000000 AND 999999999', name='check_article_9_digits'),
    sa.CheckConstraint('inner_diametr < outer_diametr', name='inner_smaller_outer'),
    sa.CheckConstraint('inner_diametr > 0', name='check_inner_diametr'),
    sa.CheckConstraint('outer_diametr > 0', name='check_outer_diametr'),
    sa.ForeignKeyConstraint(['alumoflex_id'], ['alumoflex.id'], name='fk_alumoflex'),
    sa.ForeignKeyConstraint(['construction_id'], ['construction.id'], name='fk_construction', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drennage_id'], ['drennage.id'], name='fk_drennage'),
    sa.ForeignKeyConstraint(['marker_id'], ['marker.id'], name='fk_marker'),
    sa.ForeignKeyConstraint(['twist_id'], ['twisting.id'], name='fk_twisting', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article'),
    sa.UniqueConstraint('article', name='check_article')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cable')
    op.drop_table('twisting')
    op.drop_table('construction')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('plastic')
    op.drop_table('metall')
    op.drop_table('marker')
    op.drop_table('drennage')
    op.drop_table('color')
    op.drop_table('alumoflex')
    # ### end Alembic commands ###
